apiVersion: v1  # Menggunakan API versi 1 untuk resource ConfigMap
kind: ConfigMap  # Menentukan bahwa ini adalah resource ConfigMap

metadata:
  name: mongo-config  # Nama ConfigMap yang akan digunakan dalam Kubernetes

data:
  mongo.conf: |  # Menyediakan konfigurasi MongoDB dalam bentuk file
    storage:
      dbPath: /data/db  # Menentukan path penyimpanan database MongoDB
