apiVersion: apps/v1  # Menggunakan API versi 1 untuk resource StatefulSet
kind: StatefulSet  # Menggunakan StatefulSet untuk database yang membutuhkan state persistence

metadata:
  name: mongo  # Nama StatefulSet yang akan digunakan dalam Kubernetes

spec:
  serviceName: "mongo"  # Nama Service yang digunakan untuk mengakses StatefulSet ini
  replicas: 1  # Menjalankan hanya satu instance MongoDB (single-node)

  selector:
    matchLabels:
      app: mongo  # Selector untuk mencocokkan label Pod yang dikelola oleh StatefulSet ini

  template:
    metadata:
      labels:
        app: mongo  # Label yang diberikan pada Pod yang dibuat oleh StatefulSet ini

    spec:
      containers:
      - name: mongo  # Nama container dalam Pod
        image: mongo:latest  # Image MongoDB yang digunakan dari Docker Hub (gunakan versi spesifik untuk stabilitas)

        ports:
        - containerPort: 27017  # Port default MongoDB untuk koneksi database

        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE  
          value: "/etc/mongo-credentials/MONGO_ROOT_USERNAME"  # Path file yang menyimpan username dari Secret
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE  
          value: "/etc/mongo-credentials/MONGO_ROOT_PASSWORD"  # Path file yang menyimpan password dari Secret

        volumeMounts:
        - name: mongo-storage
          mountPath: /mnt/data  # Persistent Volume untuk menyimpan data MongoDB agar tetap ada setelah Pod restart

        - name: config-volume
          mountPath: /config  # ConfigMap yang digunakan untuk menyimpan konfigurasi MongoDB

        - name: mongo-secret
          mountPath: /etc/mongo-credentials  # Secret yang digunakan untuk menyimpan kredensial MongoDB
          readOnly: true  # Secret hanya bisa dibaca, tidak bisa diubah dalam container

      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc  # Persistent Volume Claim yang digunakan untuk menyimpan data MongoDB
      - name: config-volume
        configMap:
          name: mongo-config  # ConfigMap yang digunakan untuk menyimpan konfigurasi MongoDB

      - name: mongo-secret
        secret:
          secretName: mongo-secret  # Secret yang digunakan untuk menyimpan kredensial MongoDB
