apiVersion: v1  # Menggunakan API versi 1 untuk resource Secret
kind: Secret  # Menentukan bahwa ini adalah resource Secret

metadata:
  name: mongo-secret  # Nama Secret yang akan digunakan dalam Kubernetes

type: Opaque  # Jenis Secret yang digunakan untuk menyimpan data sensitif umum

data:
  MONGO_ROOT_USERNAME: YWRtaW4=  # "admin" dalam base64
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==  # "supersecretpassword" dalam base64
