apiVersion: apps/v1  # Menggunakan API versi 1 untuk resource Deployment
kind: Deployment  # Menentukan bahwa ini adalah resource Deployment

metadata:
  name: karsajobs-backend  # Nama Deployment yang akan digunakan dalam Kubernetes

spec:
  replicas: 1  # Menentukan jumlah replika Pod untuk load balancing

  selector:
    matchLabels:
      app: karsajobs-backend  # Selector untuk mencocokkan label Pod yang dikelola oleh Deployment ini

  template:
    metadata:
      labels:
        app: karsajobs-backend  # Label yang diberikan pada Pod yang dibuat oleh Deployment ini

    spec:
      containers:
      - name: karsajobs-backend  # Nama container dalam Pod
        image: ghcr.io/abiyamakruf/karsajobs:latest  # Image container dari GitHub Container Registry (GHCR)

        ports:
        - containerPort: 8080  # Port yang diekspos oleh container di dalam Pod

        env:
        - name: APP_PORT  
          value: "8080"  # Port aplikasi yang akan digunakan di dalam container

        - name: MONGO_HOST  
          value: "mongo"  # Nama host database MongoDB, diambil dari service MongoDB dalam cluster

        - name: MONGO_USER  
          valueFrom:
            secretKeyRef:
              name: mongo-secret  # Nama Secret yang menyimpan kredensial MongoDB
              key: MONGO_ROOT_USERNAME  # Mengambil username MongoDB dari Secret

        - name: MONGO_PASS  
          valueFrom:
            secretKeyRef:
              name: mongo-secret  # Nama Secret yang menyimpan kredensial MongoDB
              key: MONGO_ROOT_PASSWORD  # Mengambil password MongoDB dari Secret
