apiVersion: apps/v1  # Menggunakan API versi 1 untuk resource Deployment
kind: Deployment  # Menentukan bahwa ini adalah resource Deployment

metadata:
  name: karsajobs-frontend  # Nama Deployment yang akan digunakan dalam Kubernetes

spec:
  replicas: 1  # Menentukan jumlah replika Pod untuk load balancing

  selector:
    matchLabels:
      app: karsajobs-frontend  # Selector untuk mencocokkan label Pod yang dikelola oleh Deployment ini

  template:
    metadata:
      labels:
        app: karsajobs-frontend  # Label yang diberikan pada Pod yang dibuat oleh Deployment ini

    spec:
      containers:
      - name: karsajobs-frontend  # Nama container dalam Pod
        image: ghcr.io/abiyamakruf/karsajobs-ui:latest  # Image container dari GitHub Container Registry (GHCR)

        ports:
        - containerPort: 8000  # Port yang diekspos oleh container di dalam Pod

        # Sudah ada file .env seharusnya tidak perlu definisikan ulang di .yml namun error di windows ketika menggunakan minikubeip:custom port
        env:
        - name: VUE_APP_BACKEND  
          value: "http://127.0.0.1:61659"  # URL backend, sesuaikan dengan NodePort Minikube
