name: CI - Karsajobs Backend

on:
  push:
    branches:
      - karsajobs-be
  pull_request:
    branches:
      - karsajobs-be

jobs:
  lint-dockerfile:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Hadolint
        run: |
          curl -sL https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 -o hadolint
          chmod +x hadolint
          sudo mv hadolint /usr/local/bin/

      - name: Run Hadolint
        run: hadolint Dockerfile

  test-app:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Run Go Unit Tests
        run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [lint-dockerfile, test-app]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/${GITHUB_ACTOR,,}/karsajobs:latest .

      - name: Push Docker Image
        run: docker push ghcr.io/${GITHUB_ACTOR,,}/karsajobs:latest
